import React from "react";
import { Document, Page, View, StyleSheet, Text } from "@react-pdf/renderer";
import GetPdfText from "./ReturnPdfText";

//Font.register({ family: "Times-Roman", src: source });

const styles = StyleSheet.create({
	title: {
		fontSize: 24,
		textAlign: "center",
		fontFamily: "Oswald",
	},
	body: {
		paddingTop: 35,
		paddingBottom: 65,
		paddingHorizontal: 35,
		flexGrow: 1,
	},
	header: {
		fontSize: 16,
		marginBottom: 20,
		textAlign: "center",
		color: "grey",
	},
	pageNumber: {
		position: "absolute",
		fontSize: 12,
		bottom: 30,
		left: 0,
		right: 0,
		textAlign: "center",
		color: "grey",
	},
	text: {
		margin: 12,
		fontSize: 14,
		fontFamily: "Times-Roman",
		textAlign: "justify",
	},
});

const DownloadPDF = (props) => {
	const text = props.text + "";
	return (
		<Document>
			<Page style={styles.body} wrap>
				<Text style={styles.header} fixed>
					Generated by Bionic Text Converter
				</Text>
				<View style={styles.body}>
					<GetPdfText text={text}></GetPdfText>
				</View>
				<Text
					style={styles.pageNumber}
					render={({ pageNumber, totalPages }) =>
						`${pageNumber} / ${totalPages}`
					}
					fixed
				/>
			</Page>
		</Document>
	);
};

export default DownloadPDF;
