import React from "react";
import { Document, Page, View, StyleSheet, Text } from "@react-pdf/renderer";
import GetPdfText from "./ReturnPdfText";

//Font.register({ family: "Times-Roman", src: source });

const styles = StyleSheet.create({
	title: {
		fontSize: 24,
		textAlign: "center",
		fontFamily: "Oswald",
	},
	body: {
		paddingTop: 35,
		paddingBottom: 65,
		paddingHorizontal: 35,
		flexGrow: 1,
	},
	row: {
		flexGrow: 1,
		flexDirection: "row",
	},
	header: {
		fontSize: 16,
		marginBottom: 20,
		textAlign: "center",
		color: "grey",
	},
});

const DownloadPDF = (props) => {
	const text = props.text + "";
	return (
		<Document>
			<Page style={styles.body}>
				<Text style={styles.header} fixed>
					Generated by Bionic Text Converter
				</Text>
				<View style={styles.body} wrap={false}>
					<View style={styles.row}>
						<GetPdfText text={text}></GetPdfText>
					</View>
				</View>
			</Page>
		</Document>
	);
};

export default DownloadPDF;
